remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: TurfWars Documentation
description: Complete documentation for the TurfWars Minecraft plugin
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
